Resources:
 instance:
  Type: AWS::EC2::Instance
  Properties: 
    ImageId: ami-0b9f27b05e1de14e9
    InstanceType: t3.micro
    IamInstanceProfile: bycresults
    KeyName: colin2024
    UserData: 
      Fn::Base64: !Sub |
          #!/bin/bash
          aws s3 cp s3://bycresults/bycresults_bootstrap.sh .
          chmod 700 bycresults_bootstrap.sh
          ./bycresults_bootstrap.sh
